version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
        - apt update -y
        
  build:
    commands:
        - mvn clean verify sonar:sonar \
               -Dsonar.projectKey=Simple-java \
               -Dsonar.projectName='Simple-java' \
               -Dsonar.host.url=https://db4fab42-4a5b-4038-af31-da16e4d01e77-10-244-8-26-9000.papa.r.killercoda.com \
               -Dsonar.token=sqp_7ec896d2fa81e0ff4c5a9c1618533bd4b3305285
        - mvn clean package
        - mkdir output
        - cp target/*.war output/books.war
artifacts:
  files:
        - 'output/*.war'
        - appspec.yaml
        - scripts/*
