version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
        - apt update -y
        
  build:
    commands:
        - mvn clean verify sonar:sonar \
           -Dsonar.projectKey=Simple-java \
           -Dsonar.projectName='Simple-java' \
           -Dsonar.host.url=https://cd0a902e-0acb-4e7a-bde7-b354ca76a35a-10-244-6-78-9000.papa.r.killercoda.com \
           -Dsonar.token=sqp_5b6f2b7033087bfab33edabe3882ab8bf3a4cdfe
        - mvn clean package
        - mkdir output
        - cp target/*.war output/books.war
artifacts:
  files:
        - 'output/*.war'
        - appspec.yaml
        - scripts/*
